apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata: { name: require-platform-pod-hardening }
spec:
  validationFailureAction: Audit
  rules:
    - name: require-resource-limits
      match: { any: [{ resources: { kinds: [Pod] } }] }
      validate:
        message: "CPU and memory limits are required."
        pattern:
          spec:
            containers:
              - resources: { limits: { memory: "?*", cpu: "?*" } }
